In [45]:
import numpy as np
ad=np.genfromtxt('DS1_C4_S2_Admission_Predict_Practice.csv',delimiter=',',skip_header=1)
print(ad)

[[  1.   337.   118.   ...   9.65   1.     0.92]
 [  2.   324.   107.   ...   8.87   1.     0.76]
 [  3.   316.   104.   ...   8.     1.     0.72]
 ...
 [398.   330.   116.   ...   9.45   1.     0.91]
 [399.   312.   103.   ...   8.78   0.     0.67]
 [400.   333.   117.   ...   9.66   1.     0.95]]


In [46]:
# TASK 1
ind=np.where(ad[:,1]>320)
print("The total number of students with GRE score greater than 320 is",np.size(ind))

The total number of students with GRE score greater than 320 is 163


In [47]:
# TASK 2
ind1=np.where(ad[:,2]>110)
print("The admission possibilities of students with TOEFL score greater than 110 are:\n",ad[ind1,8])

The admission possibilities of students with TOEFL score greater than 110 are:
 [[0.92 0.9  0.84 0.78 0.7  0.94 0.95 0.97 0.94 0.91 0.9  0.94 0.87 0.91
  0.86 0.89 0.78 0.78 0.72 0.52 0.55 0.61 0.78 0.94 0.96 0.93 0.72 0.74
  0.96 0.92 0.94 0.86 0.9  0.79 0.74 0.87 0.91 0.93 0.94 0.94 0.85 0.78
  0.84 0.92 0.96 0.79 0.89 0.8  0.9  0.92 0.97 0.8  0.81 0.83 0.96 0.93
  0.94 0.86 0.81 0.89 0.89 0.87 0.85 0.9  0.89 0.93 0.93 0.88 0.9  0.86
  0.94 0.97 0.97 0.95 0.96 0.94 0.93 0.91 0.76 0.71 0.82 0.91 0.88 0.85
  0.86 0.7  0.76 0.77 0.93 0.85 0.9  0.7  0.83 0.89 0.8  0.94 0.93 0.92
  0.89 0.86 0.9  0.71 0.8  0.79 0.8  0.81 0.8  0.8  0.83 0.94 0.93 0.91
  0.86 0.95 0.96 0.96 0.84 0.89 0.91 0.95]]


In [48]:
# TASK 3
ad1=np.sort(ad[:,1])[:-12:-1]
print(ad1)
ind2=np.where(ad[:,1]>=339)
print('The list of top 11 GRE scorer students is\n',ad[ind2])
gre2=np.sort(ad[:,2])[:-9:-1]
print(gre2)
ind3=np.where(ad[:,2]==120)
print('The list of top 8 TOEFL scorer students is\n',gre[ind3])

[340. 340. 340. 340. 340. 340. 340. 340. 339. 339. 339.]
The list of top 11 GRE scorer students is
 [[ 26.   340.   120.     5.     4.5    4.5    9.6    1.     0.94]
 [ 34.   340.   114.     5.     4.     4.     9.6    1.     0.9 ]
 [ 48.   339.   119.     5.     4.5    4.     9.7    0.     0.89]
 [ 82.   340.   120.     4.     5.     5.     9.5    1.     0.96]
 [ 85.   340.   115.     5.     4.5    4.5    9.45   1.     0.94]
 [131.   339.   114.     5.     4.     4.5    9.76   1.     0.96]
 [144.   340.   120.     4.     4.5    4.     9.92   1.     0.97]
 [149.   339.   116.     4.     4.     3.5    9.8    1.     0.96]
 [203.   340.   120.     5.     4.5    4.5    9.91   1.     0.97]
 [285.   340.   112.     4.     5.     4.5    9.66   1.     0.94]
 [385.   340.   113.     4.     5.     5.     9.74   1.     0.96]]
[120. 120. 120. 120. 120. 120. 120. 120.]
The list of top 8 TOEFL scorer students is
 [[ 26.   340.   120.     5.     4.5    4.5    9.6    1.     0.94]
 [ 82.   340.   120. 

In [49]:
# TASK 4
ind4=np.where((ad[:,1]>300)&(ad[:,1]<305)&(ad[:,4]==3.5)&(ad[:,7]==1))
print('The students who qualify for fellowship are:\n',ad[ind4])

The students who qualify for fellowship are:
 [[113.   301.   107.     3.     3.5    3.5    8.34   1.     0.62]
 [210.   301.   104.     3.     3.5    4.     8.12   1.     0.68]
 [358.   301.   104.     2.     3.5    3.5    7.89   1.     0.68]]


In [57]:
# TASK 5
scholarship=np.random.randint(5000,10000,400)
sch=np.atleast_1d(scholarship)
print(sch)

[7768 7146 9500 8296 9038 9011 9902 8375 9691 7721 9641 9080 7326 7969
 6449 7156 8238 6329 8826 5126 9987 6485 7462 6966 5449 9042 9626 8589
 6550 5799 9492 5646 6968 7208 6398 9697 6412 7717 7138 8049 7468 5274
 6305 6007 7528 9568 9021 5928 5950 7382 7443 9503 8635 5279 7533 5273
 6220 7580 9751 8883 7560 7560 6409 9555 6613 8291 9215 9089 9144 6620
 8034 7877 5306 8596 8623 7927 7364 8522 7323 6839 9108 6392 7291 8405
 7426 5904 9821 9025 9398 8873 5970 7902 7952 7101 7782 8489 9174 6089
 6794 5582 9475 5488 6840 7076 7185 9927 6388 5558 8907 6598 9565 5262
 6241 5026 8915 7222 8780 7424 6741 8446 8067 7431 5589 8090 7881 8948
 7275 8497 7244 8722 7147 8124 9087 5244 8243 5211 5968 6277 9187 8969
 6712 6471 6603 8534 7031 5553 7372 8154 5737 5044 8317 6249 9001 8306
 7348 8531 7956 5591 7550 6920 6301 9429 5391 5912 6419 6036 7020 9781
 7796 8330 8602 9296 7828 9989 7296 6039 5639 9413 5047 6454 7809 9257
 9579 5797 7927 9312 6551 8854 7340 7392 9915 9733 9303 6963 5626 7981
 7581 

In [66]:
ad = np.insert(ad, 9, sch,axis=1)
ad

array([[1.000e+00, 3.370e+02, 1.180e+02, ..., 1.000e+00, 9.200e-01,
        7.768e+03],
       [2.000e+00, 3.240e+02, 1.070e+02, ..., 1.000e+00, 7.600e-01,
        7.146e+03],
       [3.000e+00, 3.160e+02, 1.040e+02, ..., 1.000e+00, 7.200e-01,
        9.500e+03],
       ...,
       [3.980e+02, 3.300e+02, 1.160e+02, ..., 1.000e+00, 9.100e-01,
        8.012e+03],
       [3.990e+02, 3.120e+02, 1.030e+02, ..., 0.000e+00, 6.700e-01,
        5.382e+03],
       [4.000e+02, 3.330e+02, 1.170e+02, ..., 1.000e+00, 9.500e-01,
        7.652e+03]])

In [69]:
# TASK 6
ind5 = np.where(ad[:,9]>9000)
print('The SOP scores of students who recieved more than $9000 scholarship are\n',ad[ind5,4])
print('The LOR scores of students who recieved more than $9000 scholarship are\n',ad[ind5,5])

The SOP scores of students who recieved more than $9000 scholarship are
 [[3.  2.  4.5 3.  2.  3.5 4.  3.  4.5 4.5 3.  5.  5.  4.  1.5 3.  4.  3.
  3.5 3.5 2.  4.5 3.5 4.5 3.  3.5 4.  3.  3.5 4.5 5.  1.5 2.  4.  4.  3.5
  2.5 3.  4.5 4.5 4.  4.5 2.5 3.5 3.5 5.  3.5 4.  2.5 5.  4.5 4.  2.  3.5
  3.5 3.  4.  4.  2.5 2.5 5.  4.5 4.  1.  2.5 3.  2.5 4.  3.5 1.5 1.  2.5
  3.  3.  1.5 4.  2.5 1.  3.  3.  5. ]]
The SOP scores of students who recieved more than $9000 scholarship are
 [[3.5 3.  3.  4.  1.5 4.  4.5 2.  4.5 3.5 3.  5.  4.  5.  3.5 2.  3.  3.
  3.5 4.  3.  3.5 3.  3.5 3.  3.5 4.5 3.  3.5 3.  5.  3.  3.  4.5 4.5 3.5
  2.5 3.5 4.5 4.  5.  4.  3.  3.  4.  4.  3.  3.5 3.5 4.  4.  4.5 3.5 3.
  4.  2.5 4.  5.  3.  3.  4.5 4.  3.5 2.  2.  2.5 3.  3.5 3.  2.  2.5 4.
  2.  3.5 2.  3.5 3.  2.5 3.  3.5 5. ]]


In [70]:
# TASK 7
ind6 = np.where((ad[:,1]>315)&(ad[:,2]>115)&(ad[:,7]==1))
ind6

(array([  0,  22,  23,  24,  25,  32,  52,  70,  81,  97,  98, 107, 108,
        120, 121, 129, 138, 141, 143, 148, 151, 171, 176, 187, 193, 202,
        203, 212, 213, 214, 215, 259, 285, 286, 325, 337, 361, 372, 385,
        397, 399], dtype=int64),)

In [72]:
print('The serial numbers of the student eligible for scholsrship are:\n',ad[ind6,0])

The serial numbers of the student eligible for scholsrship are:
 [[  1.  23.  24.  25.  26.  33.  53.  71.  82.  98.  99. 108. 109. 121.
  122. 130. 139. 142. 144. 149. 152. 172. 177. 188. 194. 203. 204. 213.
  214. 215. 216. 260. 286. 287. 326. 338. 362. 373. 386. 398. 400.]]


In [73]:
print("There are",np.size(ind6),"such students.")

There are 41 such students.


In [74]:
ad[ind6,9]+1000

array([[ 8768.,  8462.,  7966.,  6449., 10042.,  7968.,  9635.,  9034.,
         7392.,  7089.,  7794.,  6558.,  9907.,  9067.,  8431.,  9722.,
        10187.,  7471.,  9534.,  6737.,  7249., 10296.,  6639.,  9854.,
         7963.,  8799.,  6666.,  9543.,  6387.,  9973.,  9850.,  8935.,
         7398., 10895.,  7445.,  8701., 10739.,  8223.,  6639.,  9012.,
         8652.]])

In [75]:
ad[ind6,9]=ad[ind6,9]+1000

In [76]:
ad

array([[1.000e+00, 3.370e+02, 1.180e+02, ..., 1.000e+00, 9.200e-01,
        8.768e+03],
       [2.000e+00, 3.240e+02, 1.070e+02, ..., 1.000e+00, 7.600e-01,
        7.146e+03],
       [3.000e+00, 3.160e+02, 1.040e+02, ..., 1.000e+00, 7.200e-01,
        9.500e+03],
       ...,
       [3.980e+02, 3.300e+02, 1.160e+02, ..., 1.000e+00, 9.100e-01,
        9.012e+03],
       [3.990e+02, 3.120e+02, 1.030e+02, ..., 0.000e+00, 6.700e-01,
        5.382e+03],
       [4.000e+02, 3.330e+02, 1.170e+02, ..., 1.000e+00, 9.500e-01,
        8.652e+03]])