In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
# total no of dimensions is how many elements are there in the shape
tensor = tf.constant([[[1, 2, 3], 
                      [4, 5, 6]], 
                     [[7, 8, 9], 
                      [10, 11, 12]], 
                     [[13, 14, 15], 
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
# what we have created so far:
# 1. scalar : a single number
# 2. vector : a number with direction (eg. windspeed with direction)
# 3. matrix : a 2 dimensional array of numbers
# 4. tensor : a n-dimensional array of numbers (where n can be any number, a 0 dimensional tensor is a scalar,1 dimensional tensor is a vector)

In [ ]:
# difference constant and variable:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
print("changeable_tensor: ", changeable_tensor)
print("unchangeable_tensor: ", unchangeable_tensor)

changeable_tensor:  <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
unchangeable_tensor:  tf.Tensor([10  7], shape=(2,), dtype=int32)


In [ ]:
# lets try to change the element in the tensor:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# creating a random tensor:
# random tensor are the tensor of some arbitrary size which contain random numbers
random_1 = tf.random.Generator.from_seed(42) # set seed is for reproductibility
random_1 = random_1.normal(shape = (3, 2)) # normal: tensor are normally distributed
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42) # set seed is for reproductibility
random_2 = random_2.uniform(shape = (3, 2)) # uniform: the tensor are uniformly distributed
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [ ]:
# shuffle the order of elements in a tensor:
# why do we want to shuffle the order of elements?
# so that we can initiate the random weights to the input data to help a model to learn from neural network.
not_shuffled = tf.constant([[10, 7],
                            [3, 7],
                            [2, 5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
# check dimension:
not_shuffled.ndim

2

In [ ]:
# how to shuffle a tensor in tensorflow:
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  7],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(34) # global seed
tf.random.shuffle(not_shuffled, seed = 42) # operational seed # read through a tensor flow official document

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  7]], dtype=int32)>

In [ ]:
# creating a tensor from numpy array
tf_1 = tf.ones([10, 7])
tf_1

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf_1.ndim

2

In [ ]:
tf_0 = tf.zeros(shape = (3,4))
tf_0

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf_0.ndim

2

In [ ]:
# you can also turn numpy arrays into tensors:
import numpy as np

numpy_A = np.arange(1, 25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A) # converting from numpy array into a tensor
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
A = tf.constant(numpy_A, shape = (2, 3, 4)) # adding shape
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
B = tf.constant(numpy_A, shape = (3, 8)) # adding shape
B

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [ ]:
# main difference between numpy array and tensorflow is that the tensor can run on a GPU (much faster numerical computing.)

In [ ]:
# getting information from tensors:
# e.g.: shape : the length(no of elements) of each dimension of tensor.
# e.g.: rank : the no of tensors dimensions, like rank of scalar = 0, vector = 1, matrix = 2, tensor = n
# axis or dimension : a particular dimension of a tensor.
# size : the total no of items in the tensor.

# create a rank 4 tensor(4 dimensions)
rank_4_tensor = tf.zeros(shape = [2, 3, 4, 5])
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0] # fetching zero index

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
# # get various attributes of tensor:
print('datatype of each element: ', rank_4_tensor.dtype)

datatype of each element:  <dtype: 'float32'>


In [ ]:
print('no of dimensions (rank): ', rank_4_tensor.ndim)

no of dimensions (rank):  4


In [ ]:
print('shape of tensor: ', rank_4_tensor.shape)

shape of tensor:  (2, 3, 4, 5)


In [ ]:
# tensor from 0 axis:
print("elements along the zero axis: ", rank_4_tensor[0])

elements along the zero axis:  tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)


In [ ]:
print('element along the last axis: ', rank_4_tensor[-1])

element along the last axis:  tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)


In [ ]:
print('total no of elents in th tensor: ', tf.size(rank_4_tensor.numpy()))

total no of elents in th tensor:  tf.Tensor(120, shape=(), dtype=int32)


In [ ]:
# indexing and expanding the tensor:
# tensors can be indexed as just like the python list.

some_list = [1, 2, 3, 4, 5]
some_list[:2]

[1, 2]

In [ ]:
# for rank 4 tensor:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get the first element from each dimension from each index except the final one:
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# check shapes:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# create a rank 2 tensor:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
some_list, some_list[-1]

([1, 2, 3, 4, 5], 5)

In [ ]:
rank_2_tensor[:-1]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10,  7]], dtype=int32)>

In [ ]:
# lets add in extra dimension to our rank 2 tensor:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor.shape, rank_3_tensor.ndim

(TensorShape([2, 2, 1]), 3)

In [ ]:
# alternate to tf.newaxis:
tf.expand_dims(rank_2_tensor, axis = -1) # axis = -1 means expand the final axis, or adding to the last

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# manipulating tensor using basic operation:
# +, -, *, /
# you can add a value to a tensor using addition:
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [ ]:
# we can also use tensorflow built in function:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [ ]:
# very important mathematics operation in neural network:
# matrix multiplication: matmul
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [ ]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# alternative method to do matrix multiplication:
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# lets change the shape of y for multiplication:
tf.reshape(y, shape = (2,3)) 
#3 as same shape of matrices cant be multipled, no of rows from 1st = no of columns from second matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
x.shape, tf.reshape(y, shape = (2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
# can we multiply x and y?
x@tf.reshape(y, shape = (2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# alternate method:
tf.matmul(x, tf.reshape(y, shape = (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# can we do the transpose:
x, tf.transpose(x), tf.reshape(x, shape = (2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# transposing is fliping the axis and reshaping is just reshuffling

In [ ]:
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# dot product:
# matrix multiplication is also refered to as the dot product.
# you can perform using: tf.matmul() or tf.tensordot()
# perform the dot product x and y

tf.tensordot(tf.transpose(x), y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# EXERCISE:
# 1. perform the matrix multiplication between x and transpose y.
# 2. perform the matrix multiplication between x and reshape y.
# 3. check the values of y and reshape y.

In [ ]:
# changing the data type of a tensor :
# creating a tensor with default.
B = tf.constant([1.2, 1.7])
B.dtype

tf.float32

In [ ]:
C = tf.constant([2, 3])
C.dtype

tf.int32

In [ ]:
# change from float 32 to float 16:
D = tf.cast(B, dtype = tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 1.7], dtype=float16)>,
 tf.float16)

In [ ]:
# change from float 32 to float 16:
E = tf.cast(E, dtype = tf.float32)
E, E.dtype

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([52., 38., 37.,  8., 20., 94.,  8., 60., 67., 42., 16., 33., 10.,
        90., 46., 88., 32., 87.,  1., 81., 12., 98., 45., 86., 38., 89.,
        79., 67., 82., 22.,  3., 65., 23.,  3., 53., 47., 12., 83., 98.,
        95., 62.,  9., 83., 57., 53., 14., 59., 14., 61., 47.],
       dtype=float32)>, tf.float32)

In [ ]:
E_float16 = tf.cast(E, dtype = tf.float16)
E_float16, E_float16.dtype

(<tf.Tensor: shape=(50,), dtype=float16, numpy=
 array([52., 38., 37.,  8., 20., 94.,  8., 60., 67., 42., 16., 33., 10.,
        90., 46., 88., 32., 87.,  1., 81., 12., 98., 45., 86., 38., 89.,
        79., 67., 82., 22.,  3., 65., 23.,  3., 53., 47., 12., 83., 98.,
        95., 62.,  9., 83., 57., 53., 14., 59., 14., 61., 47.],
       dtype=float16)>, tf.float16)

In [ ]:
# aggregating tensors: condensing them from multiple values down to a smaller amount of values:
# to get the absolute values:
D = tf.constant([-7, -9])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, -9], dtype=int32)>

In [ ]:
# to get the absolute values:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 9], dtype=int32)>

In [ ]:
E = tf.constant(np.random.randint(0, 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([52, 38, 37,  8, 20, 94,  8, 60, 67, 42, 16, 33, 10, 90, 46, 88, 32,
       87,  1, 81, 12, 98, 45, 86, 38, 89, 79, 67, 82, 22,  3, 65, 23,  3,
       53, 47, 12, 83, 98, 95, 62,  9, 83, 57, 53, 14, 59, 14, 61, 47])>

In [ ]:
E.ndim, tf.size(E), E.shape

(1, <tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]))

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [ ]:
tf.reduce_max(E)

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=float32, numpy=49.38>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=float32, numpy=2469.0>

In [ ]:
# EXERCISE:
# 1. with that we have learnt, find the variance and standard deviation of E tensor using tensoe flow method..

**Finding positional maximum and minimum**

In [ ]:
#create a tensor with 50 values between 0 & 1
import numpy as np
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.12723436, 0.67405914, 0.45301516, 0.44127619, 0.82417246,
       0.96344173, 0.43275294, 0.05253056, 0.29680536, 0.03003501,
       0.26220807, 0.82841705, 0.86589838, 0.68616977, 0.91652645,
       0.19495201, 0.81535963, 0.067355  , 0.84320886, 0.67165359,
       0.25062899, 0.45934426, 0.30908749, 0.70083311, 0.89259341,
       0.23625038, 0.2581593 , 0.00627639, 0.22772614, 0.11507647,
       0.93917777, 0.55206508, 0.57073046, 0.29461616, 0.89803123,
       0.52274719, 0.30012244, 0.92999597, 0.99241286, 0.5597902 ,
       0.26161138, 0.98246333, 0.94423506, 0.35342337, 0.82152299,
       0.87241642, 0.35689805, 0.87656578, 0.27298397, 0.42825553])>

In [ ]:
#Find the maximum element position of F
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=38>

In [ ]:
#find the minimum element position
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=27>

In [ ]:
# Find the maximum element position of F
print(f"The max value of F is at position:{tf.argmax(F).numpy()}")
print(f"The max value of F is: {tf.reduce_max(F).numpy()}")
print(f"Using tf.argmax() to index F, the maximum value of F is : {F[tf.argmax(F)].numpy()}")

The max value of F is at position:38
The max value of F is: 0.9924128597840569
Using tf.argmax() to index F, the maximum value of F is : 0.9924128597840569


In [ ]:
#One Hot encoding creates many features 

**ONE HOT ENCODING**

In [ ]:
#create a list of indices
some_list = [0,1,2,3]

#one hot encode them
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specify custom values on on and off encoding
tf.one_hot(some_list, depth = 4, on_value = "we are live!", off_value = "offline")


<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'we are live!', b'offline', b'offline', b'offline'],
       [b'offline', b'we are live!', b'offline', b'offline'],
       [b'offline', b'offline', b'we are live!', b'offline'],
       [b'offline', b'offline', b'offline', b'we are live!']],
      dtype=object)>

**Squaring, log, square root**

In [ ]:
# create a tensor
H = tf.constant(np.arange(1,10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
# aquaring it off
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [ ]:
# find the square root (will find error) needs to be an integer value
tf.sqrt(H)

InvalidArgumentError: ignored

In [ ]:
# change to float32
H = tf.cast(H, dtype =tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [ ]:
#Find the square root
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
#find the log (this also needs to be a float)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

**Manipulating tf.Variables tensor**

In [ ]:
#Create a  variable tensor
I = tf.Variable(np.arange(0,5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [ ]:
#Assign the final value a new value of 50
I.assign([0,1,2,3,50])
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [ ]:
#The changes happens in a place (the last value is 50 , not 4)
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

**Tensor and Numpy**

**We have seen example of tensor interact with numpy arrays to create Tensor**

**Tensor can be converted into numpy arrays**

In [ ]:
# creating a tensor in numpy arrays
J = tf.constant(np.array([3.,7.,10]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#Convert a tensor J to numpy with np.array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Convert a tensor J to numpy with .numpy()
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#create a tensor from numpy and from an array
numpy_J=tf.constant(np.array([3.,7.,10]))  #will be float 62
tensor_J=tf.constant([3.,7.,10]) #will be float 32 due to tensorflow default
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

**@tensor function**

In [ ]:
#creating a simple function
def function (x, y):
  return x ** 2 +y

  x = tf.constant(np.arange(0,10))
  y = tf.constant(np.arange(10,20))

  function(x,y)

Finding access to GPU's

In [ ]:
print(tf.config.list_physical_devices('GPU'))

[]


In [ ]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[]


In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
!pip install nvidia-smi
!pip install GPU

ERROR: Could not find a version that satisfies the requirement GPU (from versions: none)
ERROR: No matching distribution found for GPU


In [ ]:
#if you have access to a GPU , Tensorflow will automatically use it whenever possible

In [ ]:
import tensorflow as tf
print("Num of GPU avialable:", len(tf.config.experimental.list_physical_devices('GPU')))

Num of GPU avialable: 0
