**Working with files in Python**

**String Formatter**

In [1]:
name = ' Nitesh_vlogs is my yputube channel name'
follower = '30k'

In [2]:
print('name', 'follower')
print(name, follower)

name follower
 Nitesh_vlogs is my yputube channel name 30k


In [4]:
ds = [('python' ,50), ('tensorflow', 100), ('nlp', 200)]
print(ds)

[('python', 50), ('tensorflow', 100), ('nlp', 200)]


In [7]:
for info in ds:
  print(info[0], info[1])

python 50
tensorflow 100
nlp 200


In [9]:
for info in ds:
  print(f'{info[0]:{20}}, {info[1]}')

python              , 50
tensorflow          , 100
nlp                 , 200


In [20]:
for info in ds:
  print(f'{info[0]:{20}} {info[1]:.>{5}}')

python               ...50
tensorflow           ..100
nlp                  ..200


**Working with Files**

In [25]:
file = open('data.txt', 'w')

data = 'this is sentence one'
file.write(data)
file.close()

In [26]:
len(data)

20

In [27]:
file = open('data.txt', 'a')

data = '\t this is sentence three'
file.write(data)
file.close()

In [30]:
file = open('data1.txt', 'a')  # a ig file there then r+w otherwise w

data = 1
file.write(str(data))
file.close()

In [33]:
file = open('data2.txt', 'w')    # a ig file there then r+w otherwise w

data = [1,'one','this is two',2.3]
for d in data:
  file.write(str(d))
  file.write(',')
file.close()

In [34]:
with open('data3.txt','w') as file:
  data = [1,'one','this is two',2.3]
  for d in data:
    file.write(str(d))
    file.write('\n')

**Working with Read mode**

In [36]:
file = open('data3.txt','r')

In [37]:
file.seek(0)
file.read().splitlines()

['1', 'one', 'this is two', '2.3']

In [39]:
file.seek(0)
file.readlines()

['1\n', 'one\n', 'this is two\n', '2.3\n']

In [40]:
file.seek(0)
data = file.read().splitlines()
file.close()

In [41]:
data

['1', 'one', 'this is two', '2.3']

In [42]:
eval(data[-1])

2.3

In [43]:
for index, d in enumerate(data):
  try:
    data[index] = eval(d)
  except:
    pass

In [44]:
data

[1, 'one', 'this is two', 2.3]

**Reading and Writing .CSV and .TSV Files with Pandas**

In [45]:
import pandas as pd

In [50]:
pd.read_csv('data3.txt', header=None)

0
0            1
1          one
2  this is two
3          2.3

In [53]:
l = [(1, 'one'), (2, 'two'), (3, 'three')]
df = pd.DataFrame (l, columns=['digit', 'figure'])
df.to_csv('digit.csv', sep= ',' , index = False)

In [54]:
pd.read_csv('digit.csv')

digit figure
0      1    one
1      2    two
2      3  three

In [55]:
pd.read_csv('moviereviews.tsv', sep='\t')

label                                             review
0      neg  how do films like mouse hunt get into theatres...
1      neg  some talented actresses are blessed with a dem...
2      pos  this has been an extraordinary year for austra...
3      pos  according to hollywood movies made in last few...
4      neg  my first press screening of 1998 and already i...
...    ...                                                ...
1995   pos  i like movies with albert brooks , and i reall...
1996   pos  it might surprise some to know that joel and e...
1997   pos  the verdict : spine-chilling drama from horror...
1998   pos  i want to correct what i wrote in a former ret...
1999   pos  a couple of months ago , when i first download...

[2000 rows x 2 columns]

In [ ]:
df.to_csv('digit.csv', sep='\t')

**Reading and writing .XLSX Files with Pandas**

In [57]:
df.to_excel('digit_sheet.xlsx', index = None, sheet_name='digit')

In [58]:
df.to_excel('digit_sheet.xlsx', index = None, sheet_name='digit1')

In [60]:
# import xlsxwriter

ModuleNotFoundError: ignored

In [61]:
writer = pd.Excelwriter('digit_sheet.xlsx', engine = 'xlsxwriter')
df.to_excel(writer, index = None, sheet_name='digit1')
df.to_excel(writer, index = None, sheet_name='digit2')
writer.save()
writer.close()

AttributeError: ignored

In [62]:
df = pd.DataFrame({'Domain':['DataScience','CyberSecurity','Marketing'],
                   'Student_name': ['Nitesh','Jagan','Barun']})


In [63]:
df.to_excel('file.xlsx')

**Working and Writing .JSON File**

JSON (JavaScript Object Notation) is a popular data format used for representing structured data. It's common to transmit and receive data between a server and web application in JSON format.

In [64]:
import json

In [72]:
data_dict = {'one': '1', 'two': '2'}

In [73]:
type(data_dict)

dict

In [77]:
data_str = '{"one": "1", "two": "2"}'
type(data_str)

str

In [ ]:
# load(), loads(), dump(), dumps()

In [78]:
json.loads(data_str)   # it accept the json string and convert it into a dictioanry

{'one': '1', 'two': '2'}

In [80]:
json.dumps(data_dict)  # dumps a dictionary in json content 

'{"one": "1", "two": "2"}'

In [81]:
file = open('data.json', 'w')
json.dump(data_str, file)
file.close()

In [83]:
file = open('data.json', 'r')
json_data = json.load(file)
file.close()

In [84]:
json.loads(json_data)

{'one': '1', 'two': '2'}

**Extracting data from PDF**

In [85]:
!pip install PyPDF2

     |████████████████████████████████| 80 kB 3.4 MB/s 


In [86]:
import PyPDF2 as pdf

In [87]:
file = open('NLP.pdf','rb')

In [88]:
reader = pdf.PdfFileReader(file)

In [89]:
reader

In [90]:
help(reader)

Help on PdfFileReader in module PyPDF2._reader object:

class PdfFileReader(builtins.object)
 |  PdfFileReader(stream, strict=True, warndest=None, overwriteWarnings=True)
 |  
 |  Initialize a PdfFileReader object.
 |  
 |  This operation can take some time, as the PDF stream's cross-reference
 |  tables are read into memory.
 |  
 |  :param stream: A File object or an object that supports the standard read
 |      and seek methods similar to a File object. Could also be a
 |      string representing a path to a PDF file.
 |  :param bool strict: Determines whether user should be warned of all
 |      problems and also causes some correctable problems to be fatal.
 |      Defaults to ``True``.
 |  :param warndest: Destination for logging warnings (defaults to
 |      ``sys.stderr``).
 |  :param bool overwriteWarnings: Determines whether to override Python's
 |      ``warnings.py`` module with a custom implementation (defaults to
 |      ``True``).
 |  
 |  Methods defined here:
 |  
 | 

In [91]:
reader.getIsEncrypted()

False

In [92]:
reader.getDocumentInfo()

{'/Author': 's',
 '/CreationDate': 'D:20060227151709Z',
 '/Creator': 'Acrobat PDFMaker 6.0 for Word',
 '/ModDate': 'D:20060227152126Z',
 '/Producer': 'Acrobat Distiller 6.0 (Windows)',
 '/SourceModified': 'D:20060227151632',
 '/Title': '#n'}

In [93]:
reader.getNumPages()

19

In [94]:
page1 = reader.getPage(0).extractText()
page1

'Lkit: A Toolkit for \nNatua\nr\nal La\nngua\nge Interface \nConstruction \n2. \nNatural Language Processing (NLP) \nThis section \nprovides a br\nief histor\ny\n \nof \nNLP, in\ntroduces so\nme of t\nh\ne main problem\ns\n involved\n \nin extracting meaning from hu\nm\na\nn lan\nguages a\nnd exa\nm\nines the \nkind of activities perfor\nm\ne\nd\n \nby\n NLP s\ny\nstems. \n \n \n2.1. Background \nNatural language processing s\ny\nstem\ns \ntake strings\n \nof words\n (sentences) as their input and \nproduce struc\nt\nured representations capturing the \nm\ne\na\nn\ning of those \nstrings as their output. The\n \nnature of this\n outp\nu\nt \ndepends heavil\ny\n \no\nn\n the \ntask at \nhand. A \nnatu\nral language \nunderstandin\ng\n \nsy\nstem\n \nserving as an interf\nace to a dat\na\nbase \nmight \nacc\nept questions in English w\nh\nich relate t\no\n \nthe kind of \ndata held by\n the databas\ne\n. In this case\n the\n \nmeaning\n of t\nh\ne input (the \noutput \nof the \nsy\nstem\

In [95]:
with open('pdf_text.txt','w') as file1:
  for i in range(reader.getNumPages()):
    page = reader.getPage(i).extractText()
    file1.write(page)
    file1.write('\n')

**Record the Audio and Convert to Text**

In [96]:
!pip install SpeechRecognition
!conda update --force conda
!conda install pyaudio

     |████████████████████████████████| 32.8 MB 1.3 MB/s 
/bin/bash: conda: command not found
/bin/bash: conda: command not found


In [98]:
import speech_recognition as sr

In [99]:
r = sr.Recognizer()

In [ ]:
with sr.Micrphone() as source:

**Convert Audio in Text Data**

In [116]:
import speech_recognition as sr
import numpy as np
from scipy.io import wavfile

In [117]:
fs, data  =wavfile.read('laxmikant.wav')

In [112]:
fs

44100

In [113]:
data

array([[-9.1552734e-05, -9.1552734e-05],
       [-6.1035156e-05, -6.1035156e-05],
       [-6.1035156e-05, -9.1552734e-05],
       ...,
       [-1.2207031e-04, -1.8310547e-04],
       [-1.2207031e-04, -9.1552734e-05],
       [-6.1035156e-05, -9.1552734e-05]], dtype=float32)

In [118]:
y = (np.iinfo(np.int32).max * (data/np.abs(data).max())).astype(np.int32)

In [119]:
np.iinfo(np.int32).max

2147483647

In [120]:
data/np.abs(data).max()

array([[-0.00018557, -0.00018557],
       [-0.00012372, -0.00012372],
       [-0.00012372, -0.00018557],
       ...,
       [-0.00024743, -0.00037115],
       [-0.00024743, -0.00018557],
       [-0.00012372, -0.00018557]], dtype=float32)

In [121]:
y

array([[-398518, -398518],
       [-265679, -265679],
       [-265679, -398518],
       ...,
       [-531358, -797037],
       [-531358, -398518],
       [-265679, -398518]], dtype=int32)

In [122]:
wavfile.write('Nitesh.wav',fs,y)

In [123]:
r = sr.Recognizer()

In [125]:
with sr.AudioFile('Nitesh.wav') as source:
  audio = r.listen(source)

  try:
    test = r.recognize_google(audio)
    print('Working on..')
    print(test)
  except:
    print('Sorry. Try again.')


Working on..
hello everyone how are you answer all of you are enjoying these listen and I would like to also request you to please leave your rating and if you have any doubts you can come into your questions in the question-and-answer section


**Text to Speech Conversion**

In [127]:
text = 'hello everyone how are you answer all of you are enjoying these listen and I would like to also request you to please leave your rating and if you have any doubts you can come into your questions in the question-and-answer section'

In [126]:
!pip install gTTS

In [128]:
from gtts import gTTS as g

In [129]:
obj = g(text = text)
obj.save('Nitesh_gtts.mp3')

In [130]:
spanish = "Hola, te doy la bienvenida en esta lección. Dale me gusta y suscribete a este canal. Gracias"

In [131]:
obj = g(text = spanish, lang='en')
obj.save('Nitesh_spanish.mp3')

**Testing :-**

In [17]:
text= 'La maestra le pidió a Yolanda que leyera la frase en la página 10'

In [18]:
obj = gTTS(text=text, lang='en', slow=False)
obj.save('nitesh_sps_eng1.mp3')

In [66]:
!pip install google_trans_new

In [67]:
from google_trans_new import google_translator

In [68]:
text= 'La maestra le pidió a Yolanda que leyera la frase en la página 10'

In [71]:
translator = google_translator()
translate_text = translator.translate(text, lang_tgt='en')
translate_text

JSONDecodeError: ignored