In [1]:
# TASK 1
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd

In [17]:
tf.strings.join(['401642','Anurag','anurag@abc.com','9404000904','Maharashtra','M','10/05/1998'],separator="~")

<tf.Tensor: shape=(), dtype=string, numpy=b'401642~Anurag~anurag@abc.com~9404000904~Maharashtra~M~10/05/1998'>

In [2]:
# TASK 2
matrix = [['Indigo','violet','programmer', 'computer','training', 'kitchen', 'array', 'instagram', 'bluetooth']]
matrix= np.array(matrix)
print(matrix[0].reshape(3,3))

[['Indigo' 'violet' 'programmer']
 ['computer' 'training' 'kitchen']
 ['array' 'instagram' 'bluetooth']]


In [20]:
matrix = tf.constant([['Indigo','violet','programmer'],[ 'computer','training', 'kitchen'],['array', 'instagram', 'bluetooth']])
matrix

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'Indigo', b'violet', b'programmer'],
       [b'computer', b'training', b'kitchen'],
       [b'array', b'instagram', b'bluetooth']], dtype=object)>

In [3]:
# TASK 3
price = tf.constant(1895.2)
print(price)

tf.Tensor(1895.2, shape=(), dtype=float32)


In [4]:
price1 = tf.constant(1895.2, tf.float16)                       
print(price1)

tf.Tensor(1895.0, shape=(), dtype=float16)


In [5]:
# TASK 4
marks = np.round(np.random.uniform(50,100,15).reshape(-1,3),3)             
marks

array([[72.222, 92.953, 81.947],
       [67.225, 70.57 , 83.68 ],
       [94.57 , 71.729, 86.736],
       [86.8  , 73.677, 76.018],
       [96.955, 64.168, 69.517]])

In [18]:
marks1 = tf.Variable(marks, tf.int16)   
marks1

<tf.Variable 'Variable:0' shape=(5, 3) dtype=float64, numpy=
array([[72.222, 92.953, 81.947],
       [67.225, 70.57 , 83.68 ],
       [94.57 , 71.729, 86.736],
       [86.8  , 73.677, 76.018],
       [96.955, 64.168, 69.517]])>

In [19]:
for x in range(len(marks)):
  for y in range(len(marks[x])):
    marks1[x,y].assign(np.random.randint(50,100))
print(marks1)

<tf.Variable 'Variable:0' shape=(5, 3) dtype=float64, numpy=
array([[62., 52., 85.],
       [79., 58., 92.],
       [97., 53., 56.],
       [88., 59., 80.],
       [67., 71., 74.]])>


In [9]:
# TASK 5


In [10]:
# TASK 6
currency = {'India':'Rupee', 'USA':'Dollar','China':'Yuan'}
currency

{'China': 'Yuan', 'India': 'Rupee', 'USA': 'Dollar'}

In [11]:
t_currency = tf.convert_to_tensor(list(currency.items()))
print(t_currency)

tf.Tensor(
[[b'India' b'Rupee']
 [b'USA' b'Dollar']
 [b'China' b'Yuan']], shape=(3, 2), dtype=string)


In [12]:
print('Shape : ',tf.shape(t_currency))
print('Size : ',tf.size(t_currency))

Shape :  tf.Tensor([3 2], shape=(2,), dtype=int32)
Size :  tf.Tensor(6, shape=(), dtype=int32)


In [14]:
key = currency.keys()
value = currency.values()

print('Key : ',key)
print('Value :',value)

Key :  dict_keys(['India', 'USA', 'China'])
Value : dict_values(['Rupee', 'Dollar', 'Yuan'])


In [15]:
# TASK 7
unit = tf.constant(np.random.randint(1,10,4))
unit_price = tf.constant(np.random.randint(100,300,4))

print(unit)
print(unit_price)

tf.Tensor([1 1 7 2], shape=(4,), dtype=int64)
tf.Tensor([273 237 232 181], shape=(4,), dtype=int64)


In [16]:
final_price = sum(unit * unit_price)
print('Total Price : ',final_price)


Total Price :  tf.Tensor(2496, shape=(), dtype=int64)
